### ISSUE TITLE
Кривая переменная path?

### ISSUE THREAD

**Issue by mesenev** [Vring/TextRedactor#1]
`/Users/mesenev/PycharmProjects/untitled/venv/bin/python /Users/mesenev/PycharmProjects/untitled/main.py
ERROR:root:current PATH: /Users/mesenev/PycharmProjects/untitled/venv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
Traceback (most recent call last):
  File "/Users/mesenev/PycharmProjects/untitled/main.py", line 299, in <module>
    main_window = MyWidget()
  File "/Users/mesenev/PycharmProjects/untitled/main.py", line 43, in __init__
    self.ru = enchant.Dict('ru_RU')
  File "/Users/mesenev/PycharmProjects/untitled/venv/lib/python3.7/site-packages/enchant/__init__.py", line 562, in __init__
    _EnchantObject.__init__(self)
  File "/Users/mesenev/PycharmProjects/untitled/venv/lib/python3.7/site-packages/enchant/__init__.py", line 168, in __init__
    self._init_this()
  File "/Users/mesenev/PycharmProjects/untitled/venv/lib/python3.7/site-packages/enchant/__init__.py", line 569, in _init_this
    this = self._broker._request_dict_data(self.tag)
  File "/Users/mesenev/PycharmProjects/untitled/venv/lib/python3.7/site-packages/enchant/__init__.py", line 310, in _request_dict_data
    self._raise_error(eStr % (tag,),DictNotFoundError)
  File "/Users/mesenev/PycharmProjects/untitled/venv/lib/python3.7/site-packages/enchant/__init__.py", line 258, in _raise_error
    raise eclass(default)
enchant.errors.DictNotFoundError: Dictionary for language 'ru_RU' could not be found

Process finished with exit code 1`
Не работает

**Comment by UltraGreed** [comment]
I cannot reproduce this. Working fine on my machine. You are building from source. Can you please debug to find the source of the segfault?

**Comment by mesenev** [comment]
Почему в реакциях на гитхабе клоуна нет 🤡
